FROM golang:1.20 AS build

WORKDIR /app

COPY . .

RUN GOOS=linux CGO_ENABLED=1 go build -ldflags="-w -s" -o balance ./cmd/main

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y librdkafka-dev

COPY --from=build /app/balance .

CMD [ "./balance"]